cmake_minimum_required(VERSION 3.20)
project(StudyCPP)
set(CMAKE_CXX_STANDARD 17)
add_executable(rundemo
        16快排.cpp
        10三次翻转.cpp
        11多表指针.cpp
        12多表指针.cpp
        13辅助空间.cpp
        14树带权路径长度.cpp
        15辅助空间.cpp
        17树括号匹配.cpp
        18空间换时间.cpp
        19链表.cpp
        21图欧拉路径.cpp
        20三元组.cpp)